package br.edu.ifba.lucasV.avaliacao1.match;

public enum Agent {
    JETT, VIPER, BRIMSTONE, OMEN, RAZE, PHOENIX, SOVA, CYPHER, SAGE, BREACH, REYNA, KILLJOY, SKYE, YORU, ASTRA, FADE, DEADLOCK, GEKKO, NEON, HARBOR, KAY0
}
